version: '3'

services:
  rules-ui:
    image: 'rules-ui'
    # image: 'localhost:5000/rules-ui'
    build:
      context: .
    working_dir: /usr/src/app
    # Expose ports [HOST:CONTAINER}
    ports:
      - "9000:9000"
    # volumes:
    #   - .:/usr/src/app
    command: node server
    restart: always
    # Overwrite any env var defined in .env file (if required)
    environment:
      - PORT=9000
      - RULES_API=http://rules-api:4040
