version: '3'

services:
  rules-client:
    # image: 'rules-client'
    image: 'localhost:5000/rules-client'
    # build:
    #   context: .
    working_dir: /usr/src/app
    # Expose ports [HOST:CONTAINER}
    ports:
      - "9000:9000"
    # volumes:
    #   - .:/usr/src/app
    command: node server
    restart: always
    # Overwrite any env var defined in .env file (if required)
    environment:
      - PORT=9000
